//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagementForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Businesses
    {
        public string Name { get; set; }
        public int LocationID { get; set; }
        public bool ChatService { get; set; }
        public bool P2PService { get; set; }
    
        public virtual Locations Locations { get; set; }
    }
}
