//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagementForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaborators
    {
        public string UserA { get; set; }
        public string UserB { get; set; }
        public bool Following { get; set; }
        public bool Initiated { get; set; }
        public System.DateTime InitialCollaboration { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
