//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagementForms
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IdeallyConnectedTestDbEntities : DbContext
    {
        public IdeallyConnectedTestDbEntities()
            : base("name=IdeallyConnectedTestDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Businesses> Businesses { get; set; }
        public virtual DbSet<Collaborators> Collaborators { get; set; }
        public virtual DbSet<DesignSkills> DesignSkills { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<MedicalSkills> MedicalSkills { get; set; }
        public virtual DbSet<ProgrammingSkills> ProgrammingSkills { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<SpeakingSkills> SpeakingSkills { get; set; }
        public virtual DbSet<UserClaims> UserClaims { get; set; }
        public virtual DbSet<UserLocations> UserLocations { get; set; }
        public virtual DbSet<UserLogins> UserLogins { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
