//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagementForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalSkills
    {
        public System.Guid ID { get; set; }
        public string Type { get; set; }
        public bool CPR { get; set; }
        public bool EKG { get; set; }
        public bool Transfussions { get; set; }
    
        public virtual Skills Skills { get; set; }
    }
}
