//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseManagementForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skills()
        {
            this.Users = new HashSet<Users>();
        }
    
        public System.Guid ID { get; set; }
        public string Type { get; set; }
        public Nullable<byte> Expertise { get; set; }
        public string Description { get; set; }
    
        public virtual DesignSkills DesignSkills { get; set; }
        public virtual MedicalSkills MedicalSkills { get; set; }
        public virtual ProgrammingSkills ProgrammingSkills { get; set; }
        public virtual SpeakingSkills SpeakingSkills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
